/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
    App.getaQuote(0);
    }
}
